site_name: OC Process
site_url: https://awpbuild.atlnz.lc/releases/awplus-gui/cloud/docs/oc-process/
repo_url: https://github.dev/martinnzz/oc-process
theme:
  name: material

nav:
  - Home: index.md
  - 'Passwords and security':
    - Passwords: passwords.md
    - Security: security.md

plugins:
  - search
